kind: PersistentVolume
apiVersion: v1
metadata:
  name: fabric-pv
  labels:
    type: local
    name: fabricfiles
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  iscsi:
     targetPortal: 188.166.218.144
     iqn: iqn.2005-03.org.open-iscsi:2912c8d1b93
     lun: 0
     fsType: 'ext4'
