apiVersion: v1
kind: Pod
metadata:
  name: fabric-ca
spec:
  volumes:
  - name: dockersocket
    hostPath:
      path: /var/run/docker.sock
  containers:
    - name: fabricca
      image: hyperledger/fabric-ca:amd64-2.2.0
      imagePullPolicy: Always
      command: ["sh", "-c", "sleep 48h"]
      env:
      - name: FABRIC_CFG_PATH
        value: "/fabric"
      volumeMounts:
        - mountPath: /host/var/run/docker.sock
          name: dockersocket