apiVersion: v1
kind: Pod
metadata:
  name: fabric-tools
spec:
  volumes:
  - name: fabric-ca-client
    hostPath:
      path: /k8s/bins/
  - name: dockersocket
    hostPath:
      path: /var/run/docker.sock
  containers:
    - name: fabrictools
      image: hyperledger/fabric-tools:amd64-2.2.0
      imagePullPolicy: Always
      command: ["sh", "-c", "sleep 48h"]
      env:
      - name: FABRIC_CFG_PATH
        value: "/fabric"
      volumeMounts:
        - mountPath: /usr/local/bin/
          name: fabric-ca-client
        - mountPath: /host/var/run/docker.sock
          name: dockersocket
        # - mountPath: /etc/hosts
        #   name: fabricfiles
        #   subPath: ./config/hosts          
